person:
  ontology_class: "foaf:Person"
bicycle:
  ontology_class: "Bycicle"
car:
  ontology_class: "Car"
motorbike:
  ontology_class: "Motorbike"
aeroplane;:
  ontology_class: "Aeroplane"
bus:
  ontology_class: "Bus"
train:
  ontology_class: "Train"
truck:
  ontology_class: "Truck"
boat:
  ontology_class: "Boat"
traffic_light:
  ontology_class: "TrafficLight"
fire_hydrant:
  ontology_class: "FireHydrant"
stop_sign:
  ontology_class: "StopSign"
parking_meter:
  ontology_class: "ParkingMeter"
bench:
  ontology_class: "Bench"
bird:
  ontology_class: "Bird"
cat:
  ontology_class: "Cat"
dog:
  ontology_class: "Dog"
horse:
  ontology_class: "Horse"
sheep:
  ontology_class: "Sheep"
cow:
  ontology_class: "Cow"
elephant:
  ontology_class: "Elephant"
bear:
  ontology_class: "Bear"
zebra:
  ontology_class: "Zebra"
giraffe:
  ontology_class: "Giraffe"
backpack:
  ontology_class: "Backpack"
umbrella:
  ontology_class: "Umbrella"
handbag:
  ontology_class: "Handbag"
tie:
  ontology_class: "Tie"
suitcase:
  ontology_class: "Suitcase"
frisbee:
  ontology_class: "Frisbee"
skis:
  ontology_class: "Skis"
snowboard:
  ontology_class: "Snowboard"
sports_ball:
  ontology_class: "dbr:Ball"
kite:
  ontology_class: "Kite"
baseball_bat:
  ontology_class: "BaseballBat"
baseball_glove:
  ontology_class: "BaseballGlove"
skateboard:
  ontology_class: "Skateboard"
surfboard:
  ontology_class: "Surfboard"
tennis racket:
  ontology_class: "TennisRacket"
bottle:
  ontology_class: "dbr:Bottle"
wine_glass:
  ontology_class: "dbr:Glass_(drinkware)"
cup:
  ontology_class: "dbr:Cup"
fork:
  ontology_class: "dbr:Fork"
knife:
  onotology_class: "dbr:Knife"
spoon:
  ontology_class: "dbr:Spoon"
bowl:
  ontology_class: "dbr:Bowl"
banana:
  ontology_class: "dbr:Banana"
apple:
  ontology_class: "dbr:Apple"
sandwich:
  ontology_class: "Sandwich"
orange:
  ontology_class: "dbr:Orange_(fruit)"
broccoli:
  ontology_class: "Broccoli"
carrot:
  ontology_class: "Carrot"
hot dog:
  ontology_class: "HotDog"
pizza:
  ontology_class: "Pizza"
donut:
  ontology_class: "Donut"
cake:
  ontology_class: "Cake"
chair:
  ontology_class: "dbr:Chair"
couch:
  ontology_class: "dbr:Couch"
potted_plant:
  ontology_class: "dbr:Ornamental_plant"
bed:
  ontology_class: "dbr:Bed"
diningtable:
  ontology_class: "dbr:Table_(furniture)"
toilet:
  ontology_class: "Toilet"
tv:
  ontology_class: "dbr:Television"
laptop:
  ontology_class: "dbr:Laptop"
mouse:
  ontology_class: "dbr:Computer_mouse"
remote:
  ontology_class: "dbr:Remote_control"
keyboard:
  ontology_class: "dbr:Computer_keyboard"
cell_phone:
  ontology_class: "dbr:Smartphone"
microwave:
  ontology_class: "Microwave"
oven:
  ontology_class: "Oven"
toaster:
  ontology_class: "Toaster"
sink:
  ontology_class: "Sink"
refrigerator:
  ontology_class: "dbr:Refrigerator"
book:
  ontology_class: "dbr:Book"
clock:
  ontology_class: "dbr:Clock"
vase:
  ontology_class: "dbr:Vase"
scissors:
  ontology_class: "Scissors"
teddy bear:
  ontology_class: "Teddy_bear"
hair_drier:
  ontology_class: "HairDryer"
toothbrush:
  ontology_class: "Toothbrush"